import NotAllowedParameterError from './src/utils/shared/errors/NotAllowedParameter.error.js';
import { initializeVariables, isObject, isString, objectInArrayContainsId } from './src/utils/shared/functions/validateTypes.js';
import { create } from './src/main/dataSet/create.js';
import IsNotObjectError from './src/utils/shared/errors/IsNotObject.error.js';
import { doSearch } from './src/main/search/search.js';
import IsNotStringError from './src/utils/shared/errors/IsNotString.error.js';

export let dataset = {
    _array: [],
    get array() {
        return this._array;
    },
    set array(newArray) {
        try {
            if (!Array.isArray(newArray)) {
                throw new NotAllowedParameterError('newArray', 'array');
            }
            this._array = newArray;
        } catch (e) {
            if (e.type && e.description)
                console.error(`\n[${e.type}] - ${e.description}`);
            else
                console.error(e.message)
        }
    }
}

/**
 * This function generates a data set based on an array of objects. **ID field required on each object**.
 * @param {Object} main Main object with options.
 * @param {[object]} main.array Array of objects.
 * @param {string} main.nameId Name of the identification field in your objects - \'id\' by default.
 * @param {number} main.wordSize Size of the words you want to filter to generate the tags. \'2\' by default
 * @param {[string]} main.attributes Name of the attributes on the objects you need to generate the tags.
 * @return Array of objects with an array of tags on each object in the array.
 */
export function dataSetGenerate(main) {
    try {
        if (!isObject(main)) {
            throw new IsNotObjectError('main')
        }

        return generate(main);
    } catch (e) {
        if (e.type && e.description)
            console.error(`\n[${e.type}] - ${e.description}`);
        else
            console.error(e.message)
    }
}

function generate(main) {
    try {
        initializeVariables(main);
        dataset.array = [];

        if (main.array.length > 0 && objectInArrayContainsId(main.array)) {
            main.array.forEach(obj => {
                if (!obj.hasOwnProperty(main.nameId)) throw new Error(`\'${main.nameId}\' does not match the object ID field name.`);

                dataset.array.push(create(obj, main.nameId, main.wordSize, main.attributes));
            })
        }

    } catch (e) {
        if (e.type && e.description)
            console.error(`\n[${e.type}] - ${e.description}`);
        else
            console.error(e.message)
    }
    return dataset.array;
}


/**
 * This function uses user input to search for objects generated by the data set.
 * @param  input User input in a search bar.
 * @param  priorityAttribute Attribute that the search will always give priority.
 * - by default, it takes the first attribute that is considered a string in the object.
 * - Ignores identifier (ID) attributes and take the next attribute.
 * @return Returns an array with the found objects.
 */
export function search(input, priorityAttribute) {
    try {
        if (!isString(input)) {
            throw new IsNotStringError('input');
        }
        const field = (input) ? input : '';
        priorityAttribute = (priorityAttribute) ? priorityAttribute : '';
        return doSearch(field, priorityAttribute);
    } catch (e) {
        console.error(`\n[${e.type}] - ${e.description}`);

    }
}